import React, { useState, useMemo } from 'react';
import { 
  Calculator, TrendingDown, Target, AlertTriangle, Lightbulb, 
  ArrowRight, Plus, Trash2, CheckCircle2, BrainCircuit,
  Activity, Sparkles, TrendingUp, Calendar, ArrowUpCircle, Trophy, Flame, Wallet, Coins, Clock, Share2, Save, X, Edit2
} from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { createNotification } from '../lib/notifications';
import { auth } from '../lib/firebase';

interface Debt {
  id: string;
  name: string;
  balance: number;
  monthlyPayment: number;
  interestRate: number;
  dueDate: number;
}

export default function DebtPlanner({ lang }: { lang: "ar" | "en" }) {
  const isRtl = lang === "ar";
  
  const [debts, setDebts] = useState<Debt[]>([
    { id: '1', name: isRtl ? 'قرض شخصي' : 'Personal Loan', balance: 4500, monthlyPayment: 150, interestRate: 8, dueDate: 5 },
    { id: '2', name: isRtl ? 'بطاقة ائتمان' : 'Credit Card', balance: 1200, monthlyPayment: 80, interestRate: 19, dueDate: 15 },
    { id: '3', name: isRtl ? 'قرض سيارة' : 'Car Loan', balance: 8500, monthlyPayment: 250, interestRate: 6.5, dueDate: 1 },
  ]);

  const [extraPayment, setExtraPayment] = useState<number>(100);
  const [isEditing, setIsEditing] = useState(false);
  const [tempDebts, setTempDebts] = useState<Debt[]>([]);
  const [tempExtraPayment, setTempExtraPayment] = useState<number>(0);
  const [toast, setToast] = useState<{ message: string; show: boolean }>({ message: '', show: false });

  const startEditing = () => {
    setTempDebts([...debts]);
    setTempExtraPayment(extraPayment);
    setIsEditing(true);
  };

  const savePlan = async () => {
    setDebts(tempDebts);
    setExtraPayment(tempExtraPayment);
    setIsEditing(false);
    
    if (auth.currentUser) {
      await createNotification(auth.currentUser.uid, {
        title: isRtl ? "تم تحديث خطة الديون" : "Debt Plan Updated",
        message: isRtl ? "تم حفظ التعديلات على خطة سداد الديون الخاصة بك." : "Your debt repayment plan has been successfully updated.",
        category: "debt",
        type: "system"
      });
    }
  };

  const cancelEditing = () => {
    setIsEditing(false);
  };

  const addTempDebt = () => {
    const newDebt: Debt = {
      id: Date.now().toString(),
      name: isRtl ? 'دين جديد' : 'New Debt',
      balance: 0,
      monthlyPayment: 0,
      interestRate: 0,
      dueDate: 1,
    };
    setTempDebts([...tempDebts, newDebt]);
  };

  const updateTempDebt = (id: string, field: keyof Debt, value: any) => {
    setTempDebts(prev => prev.map(d => d.id === id ? { ...d, [field]: value } : d));
  };

  const removeTempDebt = (id: string) => {
    setTempDebts(prev => prev.filter(d => d.id !== id));
  };

  const handleShare = async () => {
    if (debts.length === 0) return;

    const target = sortedDebts.length > 0 ? sortedDebts[0] : null;
    const m = simulation.months;
    const yearsText = Math.floor(m / 12) > 0 ? `${Math.floor(m / 12)} ${isRtl ? 'سنة' : 'Years'}` : '';
    const monthsText = m % 12 > 0 ? `${m % 12} ${isRtl ? 'أشهر' : 'Months'}` : '';
    const andText = (yearsText && monthsText) ? (isRtl ? ' و ' : ' and ') : '';
    const payoffText = `${yearsText}${andText}${monthsText}` || (isRtl ? '0 أشهر' : '0 Months');

    const textAr = `خطة سداد الديون الخاصة بي\n\nإجمالي الديون: ${totalBalance.toLocaleString()} JOD\nالهدف الحالي: ${target?.name || 'لا يوجد'}\nمدة السداد: ${payoffText}\nالدفعة الإضافية: ${extraPayment} JOD\n\nGenerated بواسطة FinX`;
    
    const textEn = `My Debt Repayment Plan\n\nTotal Debt: ${totalBalance.toLocaleString()} JOD\nCurrent Target: ${target?.name || 'None'}\nPayoff Time: ${payoffText}\nExtra Payment: ${extraPayment} JOD\n\nGenerated by FinX`;

    const shareText = isRtl ? textAr : textEn;

    if (navigator.share) {
      try {
        await navigator.share({
          title: isRtl ? 'خطة سداد الديون' : 'Debt Repayment Plan',
          text: shareText,
        });
      } catch (err) {
        copyToClipboard(shareText);
      }
    } else {
      copyToClipboard(shareText);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setToast({ message: isRtl ? "تم نسخ الخطة بنجاح" : "Plan copied successfully", show: true });
    setTimeout(() => setToast({ message: '', show: false }), 3000);
  };

  // Sort debts smallest balance first
  const sortedDebts = useMemo(() => [...debts].sort((a, b) => a.balance - b.balance), [debts]);

  // Snowball Simulation
  const simulation = useMemo(() => {
    let currentBalances = sortedDebts.map(d => ({ ...d }));
    let months = 0;
    let timeline = [];
    let payoffDates: Record<string, number> = {};
    let totalInterestPaid = 0;

    let initialTotal = currentBalances.reduce((sum, d) => sum + d.balance, 0);
    timeline.push({ month: 0, balance: initialTotal });

    while (currentBalances.some(d => d.balance > 0) && months < 360) {
      months++;
      let extraAvailable = extraPayment;
      let monthTotalBalance = 0;

      for (let i = 0; i < currentBalances.length; i++) {
        let debt = currentBalances[i];
        if (debt.balance <= 0) continue;

        let interest = debt.balance * (debt.interestRate / 100 / 12);
        totalInterestPaid += interest;
        debt.balance += interest;

        let payment = Math.min(debt.balance, debt.monthlyPayment);
        debt.balance -= payment;
        
        if (debt.balance <= 0) {
          extraAvailable += Math.abs(debt.balance) + debt.monthlyPayment;
          debt.balance = 0;
          if (!payoffDates[debt.id]) payoffDates[debt.id] = months;
        }
        
        monthTotalBalance += debt.balance;
      }

      // Apply snowball (extra + freed minimums) to the first unpaid debt
      if (extraAvailable > 0) {
        for (let i = 0; i < currentBalances.length; i++) {
          if (currentBalances[i].balance > 0) {
            let payment = Math.min(currentBalances[i].balance, extraAvailable);
            currentBalances[i].balance -= payment;
            extraAvailable -= payment;
            monthTotalBalance -= payment;
            
            if (currentBalances[i].balance <= 0) {
               currentBalances[i].balance = 0;
               if (!payoffDates[currentBalances[i].id]) payoffDates[currentBalances[i].id] = months;
            }
          }
        }
      }

      if (months % 2 === 0 || monthTotalBalance === 0) {
        timeline.push({
          month: months,
          balance: Math.round(monthTotalBalance)
        });
      }
    }

    return { months, totalInterestPaid, timeline, payoffDates };
  }, [sortedDebts, extraPayment]);

  const totalBalance = debts.reduce((s, d) => s + d.balance, 0);
  const totalMinPayments = debts.reduce((s, d) => s + d.monthlyPayment, 0);
  const targetDebt = sortedDebts.length > 0 ? sortedDebts[0] : null;
  const nextDebt = sortedDebts.length > 1 ? sortedDebts[1] : null;

  if (debts.length === 0 && !isEditing) {
    return (
      <div className={`p-4 sm:p-5 pb-24 h-full flex flex-col overflow-y-auto no-scrollbar bg-transparent ${isRtl ? 'font-arabic text-right' : 'font-sans text-left'}`} dir={isRtl ? 'rtl' : 'ltr'}>
        <div className="flex-1 flex flex-col items-center justify-center text-center space-y-4 animate-in fade-in duration-500">
          <div className="w-20 h-20 bg-indigo-500/10 rounded-full flex items-center justify-center mx-auto mb-2 border border-indigo-500/20">
            <Calculator className="w-8 h-8 text-indigo-400" />
          </div>
          <h2 className="text-xl font-bold text-white">{isRtl ? "لا يوجد التزامات" : "No Obligations"}</h2>
          <p className="text-text-secondary text-sm leading-relaxed max-w-[250px]">
            {isRtl ? "أضف التزامات أولاً لإنشاء خطة سداد." : "Add obligations first to create a repayment plan."}
          </p>
          <button onClick={() => {
            setTempDebts([{ id: Date.now().toString(), name: isRtl ? 'دين جديد' : 'New Debt', balance: 0, monthlyPayment: 0, interestRate: 0, dueDate: 1 }]);
            setTempExtraPayment(0);
            setIsEditing(true);
          }} className="px-6 py-3 bg-white/10 hover:bg-white/20 text-white rounded-xl font-bold text-sm transition-all flex items-center justify-center gap-2 mt-4">
            <Plus className="w-4 h-4" />
            {isRtl ? "إضافة التزام جديد" : "Add New Obligation"}
          </button>
        </div>
        
        <div className="flex justify-between gap-3 pt-4 pb-6 mt-auto">
          <button disabled className="flex-1 py-3 bg-white/5 border border-white/10 text-text-secondary rounded-2xl font-bold text-xs sm:text-sm flex items-center justify-center gap-2 cursor-not-allowed">
            <Share2 className="w-4 h-4 opacity-50" />
            {isRtl ? "مشاركة الخطة" : "Share Plan"}
          </button>
          <button disabled className="flex-1 py-3 bg-white/5 border border-white/10 text-text-secondary rounded-2xl font-bold text-xs sm:text-sm flex items-center justify-center gap-2 cursor-not-allowed">
            <Edit2 className="w-4 h-4 opacity-50" />
            {isRtl ? "تعديل الخطة" : "Edit Plan"}
          </button>
        </div>
      </div>
    );
  }

  if (isEditing) {
    return (
      <div className={`p-4 sm:p-5 pb-24 h-full overflow-y-auto no-scrollbar bg-transparent ${isRtl ? 'font-arabic text-right' : 'font-sans text-left'}`} dir={isRtl ? 'rtl' : 'ltr'}>
        <div className="max-w-md mx-auto space-y-4 sm:space-y-5 animate-in slide-in-from-bottom-4 duration-300">
          
          <div className="flex items-center justify-between mb-2">
            <h1 className="text-xl font-black text-white">{isRtl ? "تعديل الخطة" : "Edit Plan"}</h1>
            <button onClick={cancelEditing} className="w-8 h-8 flex items-center justify-center bg-white/5 text-text-secondary rounded-full hover:bg-white/10 transition-colors">
              <X className="w-4 h-4" />
            </button>
          </div>

          <section className="bg-white/[0.03] border border-white/5 rounded-3xl p-5">
            <h2 className="text-sm font-bold text-white mb-4 flex items-center gap-2">
              <Wallet className="w-4 h-4 text-indigo-400" />
              {isRtl ? "القدرة على الدفع الإضافي" : "Extra Payment Capacity"}
            </h2>
            <div className="flex items-center gap-2">
              <input 
                type="number" 
                value={tempExtraPayment} 
                onChange={e => setTempExtraPayment(Number(e.target.value))}
                className="bg-black/20 text-white font-mono text-sm font-bold flex-1 outline-none border border-white/10 rounded-xl px-4 py-3 focus:border-indigo-500/50 focus:ring-1 focus:ring-indigo-500/50 transition-all"
                placeholder="0"
              />
              <span className="text-xs text-text-secondary font-sans uppercase font-bold px-2">JOD</span>
            </div>
          </section>

          <section className="space-y-3">
            <div className="flex items-center justify-between">
              <h2 className="text-sm font-bold text-white flex items-center gap-1.5">
                <Calculator className="w-4 h-4 text-indigo-400" />
                {isRtl ? "قائمة الالتزامات" : "Obligations"}
              </h2>
            </div>

            <div className="grid grid-cols-1 gap-3">
              {tempDebts.map((debt, index) => (
                <div key={debt.id} className="p-4 rounded-2xl border bg-white/[0.02] border-white/5 flex flex-col gap-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2.5 flex-1 min-w-0 pr-2">
                      <span className="w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold shrink-0 bg-white/10 text-text-secondary">{index + 1}</span>
                      <input type="text" value={debt.name} onChange={e => updateTempDebt(debt.id, "name", e.target.value)} className="bg-transparent font-bold text-sm text-white outline-none w-full truncate border-b border-white/10 focus:border-indigo-500 pb-1" placeholder={isRtl ? "اسم الدين" : "Debt Name"} />
                    </div>
                    <button onClick={() => removeTempDebt(debt.id)} className="w-7 h-7 rounded-full bg-rose-500/10 text-rose-400 flex items-center justify-center hover:bg-rose-500 hover:text-white transition-all shrink-0">
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                  
                  <div className="grid grid-cols-3 gap-2 pt-2 border-t border-white/5">
                    <div className="flex flex-col">
                      <span className="text-[8px] text-text-secondary uppercase tracking-wider mb-0.5">{isRtl ? "الرصيد" : "Balance"}</span>
                      <input type="number" value={debt.balance} onChange={e => updateTempDebt(debt.id, "balance", Number(e.target.value))} className="bg-black/20 text-white font-mono text-[11px] font-bold outline-none w-full px-2 py-1.5 rounded-lg border border-white/5 focus:border-indigo-500" />
                    </div>
                    <div className="flex flex-col">
                      <span className="text-[8px] text-text-secondary uppercase tracking-wider mb-0.5">{isRtl ? "الفائدة %" : "Interest %"}</span>
                      <input type="number" value={debt.interestRate} onChange={e => updateTempDebt(debt.id, "interestRate", Number(e.target.value))} className="bg-black/20 text-white font-mono text-[11px] font-bold outline-none w-full px-2 py-1.5 rounded-lg border border-white/5 focus:border-indigo-500" />
                    </div>
                    <div className="flex flex-col">
                      <span className="text-[8px] text-text-secondary uppercase tracking-wider mb-0.5">{isRtl ? "الحد الأدنى" : "Min Pay"}</span>
                      <input type="number" value={debt.monthlyPayment} onChange={e => updateTempDebt(debt.id, "monthlyPayment", Number(e.target.value))} className="bg-black/20 text-white font-mono text-[11px] font-bold outline-none w-full px-2 py-1.5 rounded-lg border border-white/5 focus:border-indigo-500" />
                    </div>
                  </div>
                </div>
              ))}
            </div>

            <button onClick={addTempDebt} className="w-full py-3 mt-2 flex items-center justify-center bg-white/5 hover:bg-white/10 text-indigo-400 rounded-2xl transition-colors border border-white/10 border-dashed text-sm font-bold gap-2">
              <Plus className="w-4 h-4" />
              {isRtl ? "إضافة التزام" : "Add Obligation"}
            </button>
          </section>

          <div className="flex justify-between gap-3 pt-4 pb-6">
            <button onClick={cancelEditing} className="flex-1 py-3 bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-2xl font-bold text-xs sm:text-sm transition-colors flex items-center justify-center">
              {isRtl ? "إلغاء" : "Cancel"}
            </button>
            <button onClick={savePlan} className="flex-1 py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-2xl font-bold text-xs sm:text-sm shadow-md shadow-indigo-500/20 transition-all active:scale-[0.98] flex items-center justify-center gap-2">
              <Save className="w-4 h-4" />
              {isRtl ? "حفظ التغييرات" : "Save Changes"}
            </button>
          </div>

        </div>
      </div>
    );
  }

  return (
    <div className={`p-4 sm:p-5 pb-24 h-full overflow-y-auto no-scrollbar bg-transparent ${isRtl ? 'font-arabic text-right' : 'font-sans text-left'}`} dir={isRtl ? 'rtl' : 'ltr'}>
      <div className="max-w-md mx-auto space-y-4 sm:space-y-5 animate-in fade-in duration-500">
        
        {/* 1. Header / Hero Section */}
        <section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#020617] via-[#020617] to-indigo-900/30 border border-white/5 p-5 flex flex-col justify-center shadow-xl min-h-[130px]">
          <div className="absolute top-0 right-0 w-[150px] h-[150px] bg-indigo-500/10 blur-[50px] rounded-full pointer-events-none" />
          
          <div className="relative z-10 flex flex-col gap-2.5">
            <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-indigo-500/20 border border-indigo-500/30 text-indigo-300 text-[10px] font-bold backdrop-blur-sm w-fit">
              <Sparkles className="w-3 h-3" />
              {isRtl ? "خطة سداد بكرة الثلج" : "Debt Snowball Method"}
            </div>
            <h1 className="text-xl font-black text-white tracking-tight leading-none">
              {isRtl ? "خطة السداد الذكية" : "Smart Repayment Plan"}
            </h1>
            {targetDebt && (
              <p className="text-text-secondary text-xs leading-relaxed max-w-sm mt-0.5">
                {isRtl ? `ركز هذا الشهر على ${targetDebt.name} لإغلاقه خلال ${simulation.payoffDates[targetDebt.id] || 0} أشهر.` : `Focus on ${targetDebt.name} to close it in ${simulation.payoffDates[targetDebt.id] || 0} months.`}
              </p>
            )}
          </div>
        </section>

        {/* 2. Summary Metrics Section (2x2 KPI Dashboard) */}
        <section className="grid grid-cols-2 gap-3">
          <div className="bg-white/[0.03] border border-white/5 rounded-2xl p-4 backdrop-blur-sm flex flex-col justify-center">
            <h3 className="text-[10px] text-text-secondary font-bold uppercase tracking-wider mb-1.5">{isRtl ? "إجمالي الديون" : "Total Debt"}</h3>
            <div className="text-lg font-black text-white font-mono leading-none">{totalBalance.toLocaleString()} <span className="text-[9px] text-text-secondary font-sans uppercase font-bold ml-0.5">JOD</span></div>
          </div>
          
          <div className="bg-white/[0.03] border border-white/5 rounded-2xl p-4 backdrop-blur-sm flex flex-col justify-center">
            <h3 className="text-[10px] text-text-secondary font-bold uppercase tracking-wider mb-1.5">{isRtl ? "وقت السداد" : "Payoff Time"}</h3>
            <div className="text-lg font-black text-white font-mono leading-none flex items-baseline gap-0.5">
              {Math.floor(simulation.months / 12)}<span className="text-[9px] text-text-secondary font-sans font-bold">Y</span>
              <span className="ml-1">{simulation.months % 12}</span><span className="text-[9px] text-text-secondary font-sans font-bold">M</span>
            </div>
          </div>

          <div className="bg-white/[0.03] border border-white/5 rounded-2xl p-4 backdrop-blur-sm flex flex-col justify-center">
            <h3 className="text-[10px] text-text-secondary font-bold uppercase tracking-wider mb-1.5">{isRtl ? "الحد الأدنى" : "Monthly Min"}</h3>
            <div className="text-lg font-black text-white font-mono leading-none">{totalMinPayments.toLocaleString()} <span className="text-[9px] text-text-secondary font-sans uppercase font-bold ml-0.5">JOD</span></div>
          </div>

          <div className="bg-indigo-500/10 border border-indigo-500/20 rounded-2xl p-4 backdrop-blur-sm flex flex-col justify-center">
            <h3 className="text-[10px] text-indigo-400 font-bold uppercase tracking-wider mb-1.5">{isRtl ? "الدفع الإضافي" : "Extra Payment"}</h3>
            <div className="text-lg font-black text-indigo-400 font-mono leading-none">+{extraPayment} <span className="text-[9px] text-indigo-500/50 font-sans uppercase font-bold ml-0.5">JOD</span></div>
          </div>
        </section>

        {/* 3. Current Target Debt (Centerpiece) */}
        {targetDebt && (
          <section className="bg-gradient-to-r from-indigo-900/30 to-[#020617] border border-indigo-500/20 rounded-3xl p-5 relative overflow-hidden shadow-lg mt-2">
            <div className="flex flex-col relative z-10">
              <div className="flex items-center justify-between mb-4">
                <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-indigo-500/20 text-indigo-300 text-[10px] font-bold border border-indigo-500/30">
                  <Target className="w-3 h-3 shrink-0" />
                  {isRtl ? "الهدف الحالي" : "Current Target"}
                </div>
                <span className="text-[10px] font-bold text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded-full border border-emerald-500/20">
                  {isRtl ? `متبقي ${simulation.payoffDates[targetDebt.id] || 0} أشهر` : `${simulation.payoffDates[targetDebt.id] || 0} Months Left`}
                </span>
              </div>
              <h2 className="text-xl font-black text-white mb-1.5 truncate">{targetDebt.name}</h2>
              
              <div className="flex items-end justify-between mt-4 bg-black/20 p-3.5 rounded-2xl border border-white/5">
                <div className="flex flex-col min-w-0 pr-2">
                  <span className="text-[9px] text-text-secondary font-bold uppercase tracking-wider mb-1 truncate">{isRtl ? "الرصيد المتبقي" : "Remaining"}</span>
                  <span className="text-lg sm:text-xl font-black text-white font-mono truncate">{targetDebt.balance.toLocaleString()} <span className="text-[9px] text-text-secondary font-sans uppercase">JOD</span></span>
                </div>
                <div className="flex flex-col text-left rtl:text-right border-l rtl:border-l-0 rtl:border-r border-white/10 pl-4 rtl:pl-0 rtl:pr-4 shrink-0">
                  <span className="text-[9px] text-text-secondary font-bold uppercase tracking-wider mb-1">{isRtl ? "الدفعة المستهدفة" : "Target Pay"}</span>
                  <span className="text-lg sm:text-xl font-black text-indigo-400 font-mono">{targetDebt.monthlyPayment + extraPayment} <span className="text-[9px] text-indigo-500/50 font-sans uppercase">JOD</span></span>
                </div>
              </div>
            </div>
          </section>
        )}

        {/* 4. Debt List / Repayment Plan Section (Compact) */}
        <section className="space-y-3 pt-2">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-bold text-white flex items-center gap-1.5">
              <Calculator className="w-4 h-4 text-indigo-400" />
              {isRtl ? "قائمة الالتزامات" : "Obligations"}
            </h2>
          </div>

          <div className="grid grid-cols-1 gap-3">
            {sortedDebts.map((debt, index) => {
              const isTarget = index === 0;
              return (
                <div key={debt.id} className={`p-4 rounded-2xl border flex flex-col gap-3 relative ${isTarget ? 'bg-indigo-900/10 border-indigo-500/30' : 'bg-white/[0.02] border-white/5'}`}>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2.5 flex-1 min-w-0 pr-2">
                      <span className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold shrink-0 ${isTarget ? 'bg-indigo-500 text-white shadow-sm shadow-indigo-500/20' : 'bg-white/10 text-text-secondary'}`}>{index + 1}</span>
                      <span className="font-bold text-sm text-white truncate">{debt.name}</span>
                    </div>
                  </div>
                  
                  <div className="grid grid-cols-4 gap-2 pt-2 border-t border-white/5">
                    <div className="flex flex-col">
                      <span className="text-[8px] text-text-secondary uppercase tracking-wider mb-0.5">{isRtl ? "الرصيد" : "Balance"}</span>
                      <span className="text-white font-mono text-[11px] font-bold">{debt.balance.toLocaleString()}</span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-[8px] text-text-secondary uppercase tracking-wider mb-0.5">{isRtl ? "الفائدة" : "Interest"}</span>
                      <div className="flex items-center gap-0.5">
                        <span className="text-white font-mono text-[11px] font-bold">{debt.interestRate}</span>
                        <span className="text-[8px] text-text-secondary">%</span>
                      </div>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-[8px] text-text-secondary uppercase tracking-wider mb-0.5">{isRtl ? "الدفعة" : "Min Pay"}</span>
                      <span className="text-white font-mono text-[11px] font-bold">{debt.monthlyPayment.toLocaleString()}</span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-[8px] text-text-secondary uppercase tracking-wider mb-0.5">{isRtl ? "الأشهر" : "Months"}</span>
                      <span className="text-emerald-400 font-mono text-[11px] font-bold">{simulation.payoffDates[debt.id] || 0}</span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* 5. Monthly Action Plan (Checklist) */}
        <section className="bg-white/[0.03] border border-white/5 rounded-3xl p-5 mt-2">
          <h2 className="text-sm font-bold text-white mb-4 flex items-center gap-2">
            <Calendar className="w-4 h-4 text-indigo-400" />
            {isRtl ? "خطة الشهر القادم" : "Next Month's Plan"}
          </h2>
          <div className="space-y-4">
            <div className="flex items-center justify-between bg-black/20 p-3 rounded-2xl border border-white/5">
              <span className="text-xs text-white font-bold">{isRtl ? "القدرة على الدفع الإضافي" : "Extra Capacity"}</span>
              <div className="flex items-center gap-1.5">
                <span className="bg-indigo-500/20 text-indigo-300 font-mono text-sm font-bold px-3 py-1 rounded-lg border border-indigo-500/30">
                  {extraPayment}
                </span>
                <span className="text-[9px] text-text-secondary font-sans uppercase font-bold">JOD</span>
              </div>
            </div>
            <div className="space-y-3 px-1">
              <div className="flex items-start gap-2.5 text-xs text-slate-300">
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                <span>{isRtl ? `ادفع ${extraPayment} JOD إضافية هذا الشهر` : `Pay extra ${extraPayment} JOD this month`}</span>
              </div>
              <div className="flex items-start gap-2.5 text-xs text-slate-300">
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                <span>{isRtl ? "استمر بدفع الحد الأدنى لباقي الديون" : "Continue minimum payments on the rest"}</span>
              </div>
              {targetDebt && (
                <div className="flex items-start gap-2.5 text-xs text-slate-300">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                  <span>{isRtl ? `ركز الدفع الإضافي على ${targetDebt.name}` : `Focus extra payment strictly on ${targetDebt.name}`}</span>
                </div>
              )}
            </div>
          </div>
        </section>

        {/* 6. Next Win Card */}
        {targetDebt && (
        <section className="bg-amber-500/10 border border-amber-500/20 rounded-3xl p-5 flex flex-col items-center text-center relative overflow-hidden">
          <Trophy className="w-8 h-8 text-amber-400 mb-2 drop-shadow-sm" />
          <span className="text-[10px] text-amber-500 font-bold uppercase tracking-widest mb-1.5">{isRtl ? "الانتصار القادم" : "Next Win"}</span>
          <h3 className="text-sm font-black text-white mb-3 max-w-[250px] leading-snug">{isRtl ? `${targetDebt.name} سيتم إغلاقه خلال ${simulation.payoffDates[targetDebt.id] || 0} أشهر` : `${targetDebt.name} will be closed in ${simulation.payoffDates[targetDebt.id] || 0} months`}</h3>
          <div className="flex items-center justify-center gap-1.5 text-[10px] sm:text-xs text-amber-200/90 bg-amber-500/20 px-3 sm:px-4 py-1.5 rounded-full font-medium">
            <ArrowUpCircle className="w-3.5 h-3.5 shrink-0" />
            <span>{isRtl ? `سيتحرر ${targetDebt.monthlyPayment} JOD شهرياً` : `${targetDebt.monthlyPayment} JOD freed up monthly`}</span>
          </div>
        </section>
        )}

        {/* 7. AI Advisor */}
        <section className="bg-gradient-to-r from-[#020617] to-indigo-900/20 border border-indigo-500/10 rounded-3xl p-5">
           <div className="flex items-center gap-2.5 mb-3.5">
             <BrainCircuit className="w-5 h-5 text-indigo-400" />
             <h3 className="text-sm font-black text-white">{isRtl ? "توصية FinX الذكية" : "FinX Recommendation"}</h3>
           </div>
           <ul className="space-y-2.5 text-xs text-slate-300 leading-relaxed px-1">
             <li className="flex items-start gap-2"><div className="w-1.5 h-1.5 rounded-full bg-indigo-500 mt-1.5 shrink-0 shadow-sm shadow-indigo-500/50" /><span>{isRtl ? "الاستراتيجية قوية وتقلل الفائدة المتراكمة بفاعلية." : "Strategy is solid and effectively reduces accumulated interest."}</span></li>
             <li className="flex items-start gap-2"><div className="w-1.5 h-1.5 rounded-full bg-indigo-500 mt-1.5 shrink-0 shadow-sm shadow-indigo-500/50" /><span>{isRtl ? `التركيز على ${targetDebt?.name || 'الهدف الأول'} يخلق زخماً سريعاً.` : `Focusing on ${targetDebt?.name || 'first target'} builds quick momentum.`}</span></li>
             <li className="flex items-start gap-2"><div className="w-1.5 h-1.5 rounded-full bg-indigo-500 mt-1.5 shrink-0 shadow-sm shadow-indigo-500/50" /><span>{isRtl ? "تجنب أخذ ديون جديدة خلال فترة السداد." : "Avoid taking new debts during the repayment period."}</span></li>
           </ul>
        </section>

        {/* 8. Final Action Buttons */}
        <div className="flex justify-between gap-3 pt-4 pb-6">
          <button onClick={handleShare} className="flex-1 py-3 bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-2xl font-bold text-xs sm:text-sm transition-colors flex items-center justify-center gap-2">
            <Share2 className="w-4 h-4" />
            {isRtl ? "مشاركة الخطة" : "Share Plan"}
          </button>
          <button onClick={startEditing} className="flex-1 py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-2xl font-bold text-xs sm:text-sm shadow-md shadow-indigo-500/20 transition-all active:scale-[0.98] flex items-center justify-center gap-2">
            <Edit2 className="w-4 h-4" />
            {isRtl ? "تعديل الخطة" : "Edit Plan"}
          </button>
        </div>

      </div>
      
      {toast.show && (
        <div className="fixed bottom-24 left-1/2 -translate-x-1/2 bg-emerald-500 text-white px-4 py-2 rounded-full shadow-lg text-sm font-bold z-50 animate-in fade-in slide-in-from-bottom-5">
          {toast.message}
        </div>
      )}
    </div>
  );
}
